config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
    root 'welcome#index'

  post '/update_geolocation', to: 'geocoding#update'
  # get '/selection', to: 'welcome#select'
  # get '/print', to: 'welcome#print'
    resources :clients do
      resources :locations do
        collection { post :import }
      end
      resources :expeditions do
        member do
          get :print
        end
        collection do
          get :mapping
          post :import
          get :print
        end
      end
    end

end

app/models/client.rb
class Client < ApplicationRecord
  has_many :locations, dependent: :destroy
  has_many :expeditions
  belongs_to :company
  validates :name, presence: true, uniqueness: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

    before_action :transporter_redirect, except: :index

    def index
      if current_user.clients
        @clients = current_user.clients
      end
    end

    def new
      @client = Client.new
    end

    def create
      @client = current_user.clients.new(clients_params)
      if @client.save
        redirect_to clients_path
      else
        render 'new'
      end

    end

    def edit
      @current_client = current_user.clients.find_by(id: params[:id])
    end

    def update
      @current_client = current_user.clients.find_by(id: params[:id])

      if @current_client.update_attributes(clients_params)
        redirect_to clients_path
      else
        render 'edit'
      end
    end

    def destroy
      @current_client = current_user.clients.find_by(id: params[:id])
      @current_client.destroy
      redirect_to clients_path
    end

    private

    def clients_params
      params.require(:client).permit(:name, :contact).merge(company_id: current_user.company.id)
    end

    def transporter_redirect
      if current_user.transporter?
        redirect_to clients_path
      end
    end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<h1>Edit a Client</h1>
<%= form_for @current_client, method: :patch, url: client_path(params[:id]) do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :contact %>:
  <%= f.text_field :contact %><br />

  <%= f.submit class: 'btn btn-default btn-success' %>
<% end %>

  <br>
<%= button_to('CANCEL', clients_path, method: :get, class: 'btn btn-danger') %>

app/views/clients/index.html.erb
    <header>
      <h1 id="model-name">List of clients:</h1>
    </header>
<div>
  <% if @clients %>
    <% @clients.each do |client| %>
      <ul>
        <h3><%= link_to client.name, client_locations_path(client.id), method: :get%></h3>
        <% if current_user.admin? %>
          | <%= link_to 'Edit', edit_client_path(client.id), method: :get %> | <%= link_to 'X', client_path(client.id), method: :delete,data: {confirm: "Are you sure?"}%>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>
<% if current_user.admin? %>
<h4><%= link_to 'Add new Client', new_client_path, method: :get, class: 'btn btn-primary btn-sm'%></h4>

<% end %>
<% if current_user.admin? %>

<% end %>

app/views/clients/new.html.erb
<h1>Create a new Client</h1>

  <%= form_for @client do |f| %>
    <%= f.label :name, class: 'form-group'%>:
    <%= f.text_field :name %><br />

    <%= f.label :contact,  class: 'form-group'%>:
    <%= f.text_field :contact %><br />

    <%= f.submit class: 'btn btn-default'%>
  <% end %>



<br>
<%= button_to('CANCEL', clients_path, method: :get, class: 'btn btn-danger') %>