config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
    root 'welcome#index'

  post '/update_geolocation', to: 'geocoding#update'
  # get '/selection', to: 'welcome#select'
  # get '/print', to: 'welcome#print'
    resources :clients do
      resources :locations do
        collection { post :import }
      end
      resources :expeditions do
        member do
          get :print
        end
        collection do
          get :mapping
          post :import
          get :print
        end
      end
    end

end

app/models/expedition.rb
class Expedition < ApplicationRecord

  belongs_to :origin_location, class_name: Location, foreign_key: :origin_location_id
  belongs_to :destination_location, class_name: Location, foreign_key: :destination_location_id
  belongs_to :client

  validates :origin_location_id, presence: true
  validates :destination_location_id, presence: true
  validates :weight, numericality: {less_than: 25}
  validates :state, presence: true
  validates :date, presence: true

  STATE_UNDELIVERED ="undelivered"
  STATE_DELIVERED ="delivered"
  STATE_PICKEDUP ="picked_up"
  STATE_DELIVERY ="delivery"
  STATE_CANCELED ="canceled"

  before_validation :default_values

  def default_values
    self.state ||= STATE_UNDELIVERED
  end
  
end

app/controllers/expeditions_controller.rb
require 'csv'

class ExpeditionsController < ApplicationController

    before_action :load_client
    before_action :transporter_redirect, except: [:index, :show, :update]


    def index
      @expeditions = @client.expeditions
      if params[:location_id]
        @expeditions = @expeditions.where("origin_location_id = ? OR destination_location_id = ?", params[:location_id], params[:location_id])
      end
    end

    def new
      @expedition = Expedition.new
    end

    def create
      @expedition = Expedition.new (expeditions_params)
      if @expedition.save
        redirect_to client_expeditions_path(@client)
      else
        render 'new'
      end
    end

    def show
      @expedition = Expedition.find_by(id: params[:id])
    end

    def print
      @expeditions = Expedition.all
      if params[:id]
        @expeditions = @expeditions.where(id: params[:id])
      end
    end

    def edit
      @current_expedition = Expedition.find_by(id: params[:id])
      @states = [Expedition::STATE_DELIVERED, Expedition::STATE_PICKEDUP, Expedition::STATE_CANCELED]
    end

    def update
      @current_expedition = Expedition.find_by(id: params[:id])
      if @current_expedition.update_attributes(expeditions_params_update_state)
        redirect_to client_expeditions_path(@client.id)
      else
        @states = [Expedition::STATE_DELIVERED, Expedition::STATE_PICKEDUP, Expedition::STATE_CANCELED]
        render 'edit'
      end

    end

    def destroy
      @current_expedition = Expedition.find_by(id: params[:id])
      @current_expedition.destroy
      redirect_to client_expeditions_path(@client.id)
    end

    def import

      CSV.foreach(params[:file].path, col_sep:  ";", headers: true) do |row|
        origin_location = row[0]
        destination_location = row[1]
        weight = row[2]
        state = row[3]
        date = row[4]
        if @client.locations.find_by(name: origin_location) && @client.locations.find_by(name: destination_location)
          Expedition.create(:origin_location_id => @client.locations.find_by(name: origin_location).id, :destination_location_id => @client.locations.find_by(name: destination_location).id, :weight => weight, :state => state, :date => date, :client_id => @client.id)
        end
      end
      redirect_to client_expeditions_path(@client.id), notice: "Expeditions imported correctly"
    end

    def mapping
      @expeditions = Expedition.where(date: Date.today)
    end


    private
    def expeditions_params
      params.require(:expedition).permit(:origin_location_id, :destination_location_id, :date, :weight).merge(client_id: @client.id)
    end

    def expeditions_params_update_state
      params.require(:expedition).permit(:origin_location_id, :destination_location_id, :date, :weight, :state).merge(client_id: @client.id)
    end


    def load_client
      @client = Client.find(params[:client_id])
    end

    def transporter_redirect
      if current_user.transporter?
        redirect_to client_expeditions_path(@client.id)
      end
    end
end

app/helpers/expeditions_helper.rb
module ExpeditionsHelper
  def expedition_svg(client, expedition)
    original_url = request.base_url + "/clients/#{client.id}/expeditions/#{expedition.id}"
    qr = RQRCode::QRCode.new( original_url)
    svg = qr.as_svg(offset: 0, color: '000', shape_rendering: 'crispEdges', module_size: 4)
  end

  def expedition_state_row_class(expedition)
    if expedition.state == "delivered"
      'success'
    elsif expedition.state == "picked_up"
      'warning'
    elsif expedition.state == "canceled"
      'danger'
    else
      'info'
    end

  end
end

app/views/expeditions/edit.html.erb
<h1>Edit an Expedition</h1>
<div class="form-horizontal">
  <%= form_for @current_expedition, method: :patch, url: client_expedition_path(@client, params[:id]) do |f| %>
    <%= f.label :origin_location %>:
    <%= f.select :origin_location_id, @client.locations.collect { |p| [ p.name, p.id ] }, include_blank: true , class:'form-group form-control'%>

    <%= f.label :destination_location %>:
    <%= f.select :destination_location_id, @client.locations.collect { |p| [ p.name, p.id ] }, include_blank: true , class:'form-group form-control'%> <br>

    <%= f.label :date %>:
    <%= f.date_field :date , class:'form-group form-control'%>

    <%= f.label :weight %>:
    <%= f.text_field :weight , class:'form-group form-control'%>

    <%= f.label :state %>:
    <%= f.select :state, @states.each { |state| state }, include_blank: true , class:'form-group form-control'%>

    <%= f.submit class:'btn btn-default btn-success' %>
  <% end %>
</div>
<%= button_to('CANCEL', client_expeditions_path(@client), method: :get, class: 'btn btn-danger') %>

app/views/expeditions/index.html.erb
<h1 id="model-name">Expeditions by locations:</h1>
<div class="row">
  <% if current_user.admin? %>
    <div class="col-md-6">
      <%= link_to 'Add new Expedition', new_client_expedition_path(@client), method: :get, class: 'btn btn-primary btn-sm' %>
        <h4>Import File:</h4>
      <%= form_tag import_client_expeditions_path(@client), multipart: true do %>
        <%= file_field_tag :file%> <%= submit_tag "Import file", class:'btn btn-default btn-success' %>
      <% end %>
      <br>
    </div>
  <% end %>
  <div class="col-md-3">
    <% if current_user.admin? %>
      <%= link_to('Print QR Expeditions', print_client_expeditions_path(@client), method: :get, target: "_blank", class: 'btn btn-primary') %>
      <br>
    <% end %>
    <%= button_to('Go to Locations', client_locations_path(@client), method: :get, class: 'btn btn-primary btn-warning') %>
    <br>
  </div>

  <div class="col-md-3">
    <h5 id="client"><%= @client.name %></h5>
      <%= button_to('Go to Clients', clients_path, method: :get, class: 'btn btn-primary btn-danger',style: "float: right;") %>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-condensed">
    <thead class="thead-inverse">
      <tr>
        <th>View</th>
        <% if current_user.admin? %>
          <th>Edit</th>
          <th>Delete</th>
          <th>QR Generate</th>
        <% end %>
        <th>Origin Location</th>
        <th>Destination Location</th>
        <th>Date</th>
        <th>Weight</th>
        <th>State</th>
        <th>Coordinates</th>
      </tr>
    </thead>
    <tbody>
      <% @expeditions.each do |expedition| %>
        <tr class=<%=expedition_state_row_class(expedition)%> >
          <td><%= link_to 'View', client_expedition_path(@client, expedition.id), method: :get %></td>
          <% if current_user.admin? %>
            <td><%= link_to 'Edit', edit_client_expedition_path(@client, expedition.id), method: :get %></td>
            <td><%= link_to 'X', client_expedition_path(@client, expedition.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
            <td class="qr-generation"><%= link_to('QR', print_client_expedition_path(@client, expedition), method: :get, target: "_blank") %></td>
          <% end %>
          <td><%= @client.locations.find_by(id: expedition.origin_location_id).name %></td>
          <td><%= @client.locations.find_by(id: expedition.destination_location_id).name %></td>
          <td><%= expedition.date %></td>
          <td><%= expedition.weight %></td>
          <td><%= expedition.state %></td>
          <td><%= expedition.geolocation %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to('Map Expeditions', mapping_client_expeditions_path(@client), class: 'btn btn-primary') %>

app/views/expeditions/mapping.html.erb
<h3>Today Expeditions Mapped:</h3>

<div id="map" style="width: 80%; height: 500px"></div>
    <script>

      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: {lat: 41.383502, lng: 2.160617}
        });

        <% @expeditions.each do |expedition| %>
        <% coordinates = expedition.geolocation.split(',') %>
          var myLatLng = {lat: <%=coordinates[0]%>, lng: <%=coordinates[1]%>};


          new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Hello World!'
          });
        <% end%>
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMH4O5I2hIZokyziY_CyCC-SMHkvafFV8&callback=initMap">
    </script>

app/views/expeditions/new.html.erb
<h1>Create a new Expedition</h1>
<%= form_for @expedition, url: client_expeditions_path(@client) do |f| %>

  <%= f.label :origin_location %>:
  <%= f.select :origin_location_id, @client.locations.collect { |p| [ p.name, p.id ] }, include_blank: true , class:'form-group form-control'%>

  <%= f.label :destination_location %>:
  <%= f.select :destination_location_id, @client.locations.collect { |p| [ p.name, p.id ] }, include_blank: true , class:'form-group form-control'%>
<br>
  <%= f.label :date %>:
  <%= f.date_field :date, class:'form-group form-control' %>

  <%= f.label :weight %>:
  <%= f.text_field :weight , class:'form-group form-control'%>


  <%= f.submit class:'btn btn-default btn-success'%>
<% end %>
<%= button_to('CANCEL', client_expeditions_path(@client), method: :get, class: 'btn btn-danger') %>

app/views/expeditions/print.html.erb
<% @body_onload = "window.print()" %>
<% @expeditions.each do |expedition| %>
  <div class="col-md-4">
    <h4><%= expedition.destination_location.name %></h4>
    <h5><%= expedition.destination_location.direction %></h5>
    <%= raw expedition_svg(@client, expedition) %>
  </div>
<% end %>

app/views/expeditions/show.html.erb
  <div class="row">

    <div class="col-md-6">
      <h1> Expedition nº: <%= @expedition.id %></h1>
      <h4><u>Origin Location:</u>  <%= @client.locations.find_by(id: @expedition.origin_location_id).name %></h4>
      <h4><u>Destination Location:</u>  <%= @client.locations.find_by(id: @expedition.destination_location_id).name %></h4>
      <h4><u>Date:</u>  <%= @expedition.date %></h4>
      <h4><u>Weight:</u>  <%= @expedition.weight %></h4>
      <h4><u>State:</u>  <%= @expedition.state %></h4>
    </div>

  </div>

  <div class="row">
      <%= link_to('Delivered', client_expedition_path(@client, @expedition, expedition: {state: 'delivered'}), method: :patch, class: 'btn btn-default btn-lg btn-success') %>
  </div>

  <div class="row">
      <%= link_to('Picked Up', client_expedition_path(@client, @expedition, expedition: {state: 'picked_up'}), method: :patch, class: 'btn btn-default btn-lg btn-warning') %>
  </div>

    <div class="row">
        <%= link_to('Canceled', client_expedition_path(@client, @expedition, expedition: {state: 'canceled'}), method: :patch, class: 'btn btn-default btn-lg btn-danger') %>
    </div>