config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
    root 'welcome#index'

  post '/update_geolocation', to: 'geocoding#update'
  # get '/selection', to: 'welcome#select'
  # get '/print', to: 'welcome#print'
    resources :clients do
      resources :locations do
        collection { post :import }
      end
      resources :expeditions do
        member do
          get :print
        end
        collection do
          get :mapping
          post :import
          get :print
        end
      end
    end

end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :client

  has_many :origin_expeditions, class_name: Expedition , foreign_key: :origin_location_id
  has_many :destination_expeditions, class_name: Expedition , foreign_key: :destination_location_id

  validates :name, uniqueness: true, presence: true
  validates :direction, presence: true
  validates :client_id, presence: true
  validates :internal_code, uniqueness: true, presence: true

end

app/controllers/locations_controller.rb
require 'csv'
class LocationsController < ApplicationController

    before_action :load_client
    before_action :transporter_redirect, except: :index

    def index
      @locations = @client.locations
    end

    def new
      @location = Location.new
    end

    def create
      @location = Location.new (locations_params)
      if @location.save
        redirect_to client_locations_path(params[:client_id])
      else
        render 'new'
      end

    end

    def edit
      @current_location = Location.find_by(id: params[:id])
    end

    def update
      @current_location = Location.find_by(id: params[:id])
      if @current_location.update_attributes(locations_params)
        redirect_to client_locations_path(params[:client_id])
      else
        render 'edit'
      end

    end

    def destroy
      @current_location = Location.find_by(id: params[:id])
      @current_location.destroy
      redirect_to client_locations_path
    end

    def import
      CSV.foreach(params[:file].path, col_sep:  ";", headers: true) do |row|
        internal_code = row[0]
        name = row[1]
        direction = row[2]
        postal_code = row[3]
        hour_in = row[4]
        hour_out = row[5]
        contact = row[6]
        route = row[7]
        if Location.find_by(internal_code: internal_code)
          Location.find_by(internal_code: internal_code).update_attributes(:name => name, :internal_code => internal_code, :direction => direction, :postal_code => postal_code, :hour_in => hour_in, :hour_out => hour_out, :contact => contact, :route => route)

        else
          Location.create(:name => name, :internal_code => internal_code, :direction => direction, :postal_code => postal_code, :hour_in => hour_in, :hour_out => hour_out, :contact => contact, :route => route, :client_id => params[:client_id])
        end
      end
      redirect_to client_locations_path, notice: "Data imported correctly"
    end

    private
    def locations_params
      params.require(:location).permit(:name, :internal_code, :direction, :postal_code, :hour_in, :hour_ut, :contact, :route).merge(client_id: params[:client_id])
    end

    def load_client
      @client = Client.find(params[:client_id])
    end

    def transporter_redirect
      if current_user.transporter?
        redirect_to client_locations_path(@client.id)
      end
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/edit.html.erb
<h1>Edit a Location</h1>
<div class="form-horizontal col-md-6">
  <%= form_for @current_location, url: client_location_path(params[:client_id]) do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name, class:'form-group form-control' %><br />

    <%= f.label :internal_code %>:
    <%= f.text_field :internal_code, class:'form-group form-control' %><br />

    <%= f.label :direction %>:
    <%= f.text_field :direction, class:'form-group form-control' %><br />

    <%= f.label :postal_code %>:
    <%= f.text_field :postal_code, class:'form-group form-control' %><br />

    <%= f.label :hour_in %>:
    <%= f.time_field :hour_in, class:'form-group form-control' %><br />

    <%= f.label :hour_out %>:
    <%= f.time_field :hour_out, class:'form-group form-control' %><br />

    <%= f.label :contact %>:
    <%= f.text_field :contact, class:'form-group form-control' %><br />

    <%= f.label :route %>:
    <%= f.text_field :route, class:'form-group form-control' %><br />

    <%= f.submit class: 'btn btn-default btn-success'%>
  <% end %>
  <br>
  <%= button_to('CANCEL', client_locations_path(@client), method: :get, class: 'btn btn-danger') %>
</div>

app/views/locations/index.html.erb
<h1 id="model-name">List of locations:</h1>
<div class="row">
  <% if current_user.admin? %>
    <div class="col-md-6">
    <%= link_to 'Add new Location', new_client_location_path, method: :get, class: 'btn btn-primary btn-sm' %>
      <h4>Import File:</h4>
      <%= form_tag import_client_locations_path(@client), multipart: true do %>
        <%= file_field_tag :file%> <%= submit_tag "Import file", class: 'btn btn-default btn-success'%>
      <% end %>
      <br>
    </div>
  <% end %>

  <div class="col-md-3">
    <h3>Expeditions:</h3>
    <%= link_to 'See all the expeditions', client_expeditions_path(client_id: @client.id), method: :get, class: 'btn btn-primary btn-xs'%>
  </div>
  <div class="col-md-3">
    <h5 id="client"><%= @client.name %></h5>
      <%= button_to('Go to Clients', clients_path, method: :get, class: 'btn btn-primary btn-danger',style: "float: right;") %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-condensed">
  <thead class="thead-inverse">
    <tr>
      <% if current_user.admin? %>
        <th>Edit</th>
        <th>Delete</th>
      <% end %>
      <th>Expeditions</th>
      <th>Code</th>
      <th>Name</th>
      <th>Direction</th>
      <th>Zip Code</th>
      <th> Hour In</th>
      <th>Hour Out</th>
      <th>Contact</th>
      <th>route</th>
    </tr>
  </thead>
  <tbody>


    <% @locations.each do |location| %>
      <tr>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_client_location_path(@client, location), method: :get %></td>
          <td><%= link_to 'X', client_location_path(@client, location), method: :delete, data: {confirm: "Are you sure?"}%></td>
        <% end %>
        <td><%= link_to 'View', client_expeditions_path(@client, location_id: location.id), method: :get %></td>
        <td><%= location.internal_code %></td>
        <td><%= location.name %></td>
        <td><%= location.direction %></td>
        <td><%= location.postal_code %></td>
        <td><%= location.hour_in %></td>
        <td><%= location.hour_out %></td>
        <td><%= location.contact %></td>
        <td><%= location.route %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/locations/new.html.erb
<h1>Create a new Location</h1>
<div class="form-horizontal col-md-6">
  <%= form_for @location, url: client_locations_path(params[:client_id]) do |f| %>
    <div class="form-group">
      <%= f.label :name %>:
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :internal_code %>:
      <%= f.text_field :internal_code, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :direction %>:
      <%= f.text_field :direction, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :postal_code %>:
      <%= f.text_field :postal_code, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :hour_in %>:
      <%= f.time_field :hour_in, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :hour_out %>:
      <%= f.time_field :hour_out, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :contact %>:
      <%= f.text_field :contact, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :route %>:
      <%= f.text_field :route, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-default'%>
  <% end %>
  <br>
  <%= button_to('CANCEL', client_locations_path(@client), method: :get, class: 'btn btn-danger') %>
</div>